// ──────────────────────────────────────────────────────────────────────────────
// firebase_options.dart  –  PLACEHOLDER
// ──────────────────────────────────────────────────────────────────────────────
//
// This file is auto-generated by the FlutterFire CLI.
// Replace this file with the real one by running:
//
//   flutterfire configure
//
// Prerequisites:
//   dart pub global activate flutterfire_cli
//   firebase login
//   # Then inside the project root:
//   flutterfire configure --project=YOUR_FIREBASE_PROJECT_ID
//
// The command will regenerate this file with your real project credentials.
// ──────────────────────────────────────────────────────────────────────────────

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android: return android;
      case TargetPlatform.iOS:     return ios;
      case TargetPlatform.macOS:   return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ── REPLACE ALL VALUES BELOW after running `flutterfire configure` ──────────

  static const FirebaseOptions web = FirebaseOptions(
    apiKey:            'REPLACE_WITH_WEB_API_KEY',
    appId:             'REPLACE_WITH_WEB_APP_ID',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId:         'REPLACE_WITH_PROJECT_ID',
    authDomain:        'REPLACE_WITH_PROJECT_ID.firebaseapp.com',
    storageBucket:     'REPLACE_WITH_PROJECT_ID.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey:            'REPLACE_WITH_ANDROID_API_KEY',
    appId:             'REPLACE_WITH_ANDROID_APP_ID',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId:         'REPLACE_WITH_PROJECT_ID',
    storageBucket:     'REPLACE_WITH_PROJECT_ID.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey:            'REPLACE_WITH_IOS_API_KEY',
    appId:             'REPLACE_WITH_IOS_APP_ID',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId:         'REPLACE_WITH_PROJECT_ID',
    storageBucket:     'REPLACE_WITH_PROJECT_ID.firebasestorage.app',
    iosClientId:       'REPLACE_WITH_IOS_CLIENT_ID',
    iosBundleId:       'com.neighbourgo.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey:            'REPLACE_WITH_MACOS_API_KEY',
    appId:             'REPLACE_WITH_MACOS_APP_ID',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId:         'REPLACE_WITH_PROJECT_ID',
    storageBucket:     'REPLACE_WITH_PROJECT_ID.firebasestorage.app',
    iosClientId:       'REPLACE_WITH_MACOS_CLIENT_ID',
    iosBundleId:       'com.neighbourgo.app',
  );
}
